### ISSUE TITLE
模型的参数设置问题

### ISSUE THREAD

**Issue by jyf123** [Cartus/Latent-Forests#1]
你好，我对您的这篇论文很感兴趣，因此进行了代码复现
想问下cpr，pgr，sem保存的这三个最好的模型对应的训练参数都是代码默认的参数吗（batch_size,learning_rate等）
如果不是，可以提供一下最好的模型对应的参数设置吗

**Comment by Cartus** [comment]
Hi, hyper-parameters used for training models are written in there three files: train_cpr.sh, train_pgr.sh, and train_sem.sh. They should be the default hyper-parameters for the pre-trained models.

**Comment by jyf123** [comment]
ok，thanks！
